//
//
// File auto-generated by envgenerator
// Change properties by generating a new file using the provided options
//
// envgenerator created by Mark Jarecki 2019
//
//

public enum Environments {
	 case development
	 case testflight
	 case appstore
}

public let environment: Environments = .development 
