//
//  FLXAutoText.swift
//
//  Created by Mark Jarecki on 30/8/19.
//

import Foundation

public struct FLXAutoText: AutoTextable {

    // MARK: - AutoTextable conformance

    public static let text: String = """
    //
    //
    // File auto-generated by envgenerator
    // Change properties by generating a new file using the provided options
    //
    // envgenerator created by Mark Jarecki 2019
    //
    //
    

    """
    
}

